# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x03\x61pp\"\x86\x01\n\rInventoryItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x16\n\x0estock_quantity\x18\x03 \x01(\x05\x12\x15\n\rreorder_level\x18\x04 \x01(\x05\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\"\x87\x01\n\x0fStockAdjustment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x19\n\x11inventory_item_id\x18\x02 \x01(\x05\x12\x17\n\x0f\x61\x64justment_type\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x0e\n\x06reason\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"\x97\x01\n\x12InventoryOperation\x12%\n\toperation\x18\x01 \x01(\x0e\x32\x12.app.OperationType\x12*\n\x0einventory_item\x18\x02 \x01(\x0b\x32\x12.app.InventoryItem\x12.\n\x10stock_adjustment\x18\x03 \x01(\x0b\x32\x14.app.StockAdjustment*3\n\rOperationType\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPERATIONTYPE._serialized_start=453
  _OPERATIONTYPE._serialized_end=504
  _INVENTORYITEM._serialized_start=25
  _INVENTORYITEM._serialized_end=159
  _STOCKADJUSTMENT._serialized_start=162
  _STOCKADJUSTMENT._serialized_end=297
  _INVENTORYOPERATION._serialized_start=300
  _INVENTORYOPERATION._serialized_end=451
# @@protoc_insertion_point(module_scope)
